### PR TITLE
fix: tailwind setup issues

### PR DESCRIPTION
**Pull request by gabrielelpidio**

### CODE REVIEW

**Comment by RhysSullivan** [comment]
If you update the TSConfig file to match below it'll fix shadcn cli not working

```json
  "paths": {
      "@/*": [
        "./*"
      ]
    }
```

**Comment by gabrielelpidio** [comment]
@RhysSullivan Didn't catch that one, updated the pr

**Comment by RhysSullivan** [comment]
TDD actually stands for Twitter Driven Development

**Comment by JacobMGEvans** [comment]
lmao I merged in Shanes, if he missed anything feel free to rebase and add it

**Comment by gabrielelpidio** [comment]
Closing it, Shanes had everything, glad that it was resolved TDD ftw

**Pull request closed without merging**
